# Generated by Django 3.1.3 on 2020-12-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(default='', max_length=300)),
                ('hashedPassword', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Entries_Qrcodes_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(default='', max_length=300)),
                ('password', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Qrcode_Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Qrcode_Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode_id', models.IntegerField()),
                ('establishment_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(default='', max_length=300)),
                ('hashedPassword', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
