# Generated by Django 3.1.3 on 2020-12-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('expire_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('telephone', models.CharField(default='', max_length=13)),
                ('street_name', models.CharField(default='', max_length=100)),
                ('house_number', models.IntegerField()),
                ('postcode', models.CharField(default='', max_length=10)),
                ('inami', models.CharField(default='', max_length=20)),
                ('mail', models.CharField(default='', max_length=100)),
                ('hashedPassword', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Entries_Qrcodes_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('telephone', models.CharField(default='', max_length=13)),
                ('street_name', models.CharField(default='', max_length=100)),
                ('house_number', models.IntegerField()),
                ('postcode', models.CharField(default='', max_length=10)),
                ('tva', models.CharField(default='', max_length=20)),
                ('mail', models.CharField(default='', max_length=100)),
                ('hashedPassword', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('phone_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Qrcode_Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Qrcode_Establishment',
            fields=[
                ('qrcode_id', models.IntegerField(primary_key=True, serialize=False)),
                ('establishment_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
